blank_issues_enabled: true
contact_links:
  - name: WLED Discord community
    url: https://discord.gg/KuqP7NE
    about: Please ask and answer questions and discuss setup issues here.
  - name: WLED community forum
    url: https://wled.discourse.group/
    about: For issues and ideas that might need longer discussion.
  - name: Kno.wled.ge base
    url: https://github.com/Aircoookie/WLED/wiki/FAQ
    about: Take a look at the frequently asked questions and documentation, perhaps your question is already answered!